web/router.ex
defmodule Quizler.Router do
  use Quizler.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Quizler.Logger, repo: Quizler.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/users", Quizler do
    pipe_through :browser

    get "/login", SessionController, :new
    post "/login", SessionController, :create

    get "/", UserController, :index
    get "/signup", UserController, :new
    post "/", UserController, :create
    get "/:id", UserController, :show
    delete "/", UserController, :delete
    
    get "/auth/:provider", AuthController, :request
    get "/auth/:provider/callback", AuthController, :callback

    delete "/logout", SessionController, :delete
  end

  scope "/", Quizler do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", PageController, :about

    get "/training", GroupController, :index
    get "/decks/:id/terms/json", DeckController, :terms_json
    get "/decks/:id/terms", DeckController, :terms
    get "/decks/:deck_id/quiz/done", DeckController, :done_quiz
    post "/decks/:deck_id/quiz/done", DeckController, :done_quiz
    get "/decks/:id/quiz", DeckController, :quiz
    get "/decks/:id/quiz_items", DeckController, :quiz_items
    get "/decks/:id/done", DeckController, :done_flashcard
    get "/decks/:deck_id/games/match/cards", Deck.GameController, :game_match_cards
    get "/decks/:deck_id/games/match", Deck.GameController, :game_match
    get "/decks/:deck_id/games/match/done", Deck.GameController, :game_match_done

    get "/groups/all", GroupController, :all
    get "/groups/:id/test", GroupController, :test
    get "/groups/:id/test_items", GroupController, :test_items
    get "/groups/:id/terms", GroupController, :terms
    get "/groups/test_results", GroupController, :test_results
    delete "/groups/test_results/:test_result_id", GroupController, :delete_test_result

    post "/groups/:group_id/test/done", GroupController, :test_done
    resources "/terms", TermController
    resources "/groups", GroupController
    resources "/decks", DeckController
    resources "/logs", LogController

    resources "/test_groups", UserTestGroupController

    resources "/spanish_terms", SpanishTermController

    get "/exams/code/:code", ExamController, :code
    resources "/exams/questions", ExamQuestionController
    get "/exams/results", ExamController, :results
    delete "/exams/results/:result_id", ExamController, :delete_result
    get "/exams/:id/questions", ExamController, :questions
    post "/exams/:exam_id/done", ExamController, :done
    resources "/exams/question_types", ExamQuestionTypeController

    resources "/exams", ExamController
    resources "/user_languages", UserLanguageController
    resources "/languages", LanguageController
    resources "/term_sentences", TermSentenceController
  end


  # Other scopes may use custom stacks.
  # scope "/api", Quizler do
  #   pipe_through :api
  # end
end

web/user/session_controller.ex
defmodule Quizler.SessionController do
    use Quizler.Web, :controller
    plug :scrub_params, "session" when action in [:create]

    def new(conn, _params) do
      render(conn, "new.html")
    end

    def create(conn,  %{"session" => params}) do
      case user_by_email(params) do
        {:ok, user} ->
          conn
          |> Quizler.Authorizer.login(user)
        {:error, :provider} ->
            conn
            |> put_flash(:error, "Please login with your Google account")
            |> render("new.html")
        _ ->
          conn
          |> put_flash(:error, "Invalid email/password combination")
          |> render("new.html")
      end
    end

    defp user_by_email(params) do
      user = Repo.get_by(Quizler.User, email: params["email"])
      cond do
        user && (user.password_hash == nil) ->
          {:error, :provider}
        user && Comeonin.Bcrypt.checkpw(params["password"], user.password_hash) ->
          {:ok, user}
        true ->
          {:error, :not_found}
      end
    end

    def delete(conn, _) do
      conn
      |> configure_session(drop: true)
      |> put_flash(:info, "You are logged out!")
      |> redirect(to: "/")
    end
end

web/views/user_view.ex
defmodule Quizler.UserView do
  use Quizler.Web, :view

end

web/templates/user/index.html.eex
<h2>Users</h2>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td class="text-right">
        <%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/user/new.html.eex
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />

<div class="center_everything">
<div class="user">
  <h1>Sign up</h1>
  <div class="social row">
    <a href="/users/auth/google">
      <div class="google">
        <img src="/images/social/google.svg">
        <span>Sign up with Google+</span>
      </div>
    </a>
  </div>

  <h4>Or sign up with</h4>
  <%= form_for @changeset, user_path(@conn, :create), fn f -> %>
    <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
      </div>
    <% end %>

    <div class="form-group row">
      <%= label f, :name, class: "control-label col-md-2" %>
      <div class="col-md-9">
        <%= text_input f, :name, class: "form-control", required: true %>
        <%= error_tag f, :name %>
      </div>
    </div>

    <div class="form-group row">
      <%= label f, :email, class: "control-label col-md-2" %>
      <div class="col-md-9">
        <%= email_input f, :email, class: "form-control", required: true %>
        <%= error_tag f, :email %>
      </div>
    </div>

    <div class="form-group row">
      <%= label f, :password, class: "control-label col-md-2" %>
      <div class="col-md-9">
        <%= password_input f, :password, class: "form-control", required: true %>
        <%= error_tag f, :password %>
      </div>
    </div>

    <div class="form-group row">
      <%= label f, :retype_password, class: "control-label col-md-2" %>
      <div class="col-md-9">
        <%= password_input f, :password_confirmation, class: "form-control", required: true %>
        <%= error_tag f, :password_confirmation %>
      </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-2">Secondary Language</label>
      <div class="col-md-9">
        <%= multiple_select f, :languages, @languages, class: "multiple_select" %>
      </div>
    </div>

    <div class="form-group row">
      <%= submit "Sign up", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script type="text/javascript">
  $('.multiple_select').select2({
      tags: true
    });
</script>

web/templates/user/show.html.eex
<ul>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>
  <li>
    <strong>Languages</strong>
    <ul>
      <%= for language <- @user.languages do %>
        <li><%= language %></li>
      <% end %>
    </ul>
  </li>
</ul>