web/router.ex
defmodule Quizler.Router do
  use Quizler.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Quizler.Logger, repo: Quizler.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/users", Quizler do
    pipe_through :browser

    get "/login", SessionController, :new
    post "/login", SessionController, :create

    get "/", UserController, :index
    get "/signup", UserController, :new
    post "/", UserController, :create
    get "/:id", UserController, :show
    delete "/", UserController, :delete
    
    get "/auth/:provider", AuthController, :request
    get "/auth/:provider/callback", AuthController, :callback

    delete "/logout", SessionController, :delete
  end

  scope "/", Quizler do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", PageController, :about

    get "/training", GroupController, :index
    get "/decks/:id/terms/json", DeckController, :terms_json
    get "/decks/:id/terms", DeckController, :terms
    get "/decks/:deck_id/quiz/done", DeckController, :done_quiz
    post "/decks/:deck_id/quiz/done", DeckController, :done_quiz
    get "/decks/:id/quiz", DeckController, :quiz
    get "/decks/:id/quiz_items", DeckController, :quiz_items
    get "/decks/:id/done", DeckController, :done_flashcard
    get "/decks/:deck_id/games/match/cards", Deck.GameController, :game_match_cards
    get "/decks/:deck_id/games/match", Deck.GameController, :game_match
    get "/decks/:deck_id/games/match/done", Deck.GameController, :game_match_done

    get "/groups/all", GroupController, :all
    get "/groups/:id/test", GroupController, :test
    get "/groups/:id/test_items", GroupController, :test_items
    get "/groups/:id/terms", GroupController, :terms
    get "/groups/test_results", GroupController, :test_results
    delete "/groups/test_results/:test_result_id", GroupController, :delete_test_result

    post "/groups/:group_id/test/done", GroupController, :test_done
    resources "/terms", TermController
    resources "/groups", GroupController
    resources "/decks", DeckController
    resources "/logs", LogController

    resources "/test_groups", UserTestGroupController

    resources "/spanish_terms", SpanishTermController

    get "/exams/code/:code", ExamController, :code
    resources "/exams/questions", ExamQuestionController
    get "/exams/results", ExamController, :results
    delete "/exams/results/:result_id", ExamController, :delete_result
    get "/exams/:id/questions", ExamController, :questions
    post "/exams/:exam_id/done", ExamController, :done
    resources "/exams/question_types", ExamQuestionTypeController

    resources "/exams", ExamController
    resources "/user_languages", UserLanguageController
    resources "/languages", LanguageController
    resources "/term_sentences", TermSentenceController
  end


  # Other scopes may use custom stacks.
  # scope "/api", Quizler do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Quizler.LayoutView do
  use Quizler.Web, :view


end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>UnoNY</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <header>
      <nav class="navbar">
        <div class="navbar-brand">
          <a href="/"><img src="/images/logo.png" /></a>
        </div>
        <button class="navbar-toggler hidden-md-up pull-xs-right" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header">
          Menu <span class="icon">&#9776;</span>
        </button>
        <div class="clearfix hidden-md-up"></div>
        <div class="collapse navbar-toggleable-sm" id="navbar-header">

          <ul class="nav navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="/about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/training">Training</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/exams">Sample Exams</a>
            </li>
            <%= if admin?(@conn) do %>
            <li class="nav-item">
              <a class="nav-link" href="/logs">Logs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users">Users</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/groups/all">Section</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/decks">Lesson</a>
            </li>

            <% end %>
          </ul>

          <div class="user-nav pull-md-right">
            <%= if logged_in?(@conn) do %>
              <div class="hidden-md-down">
                <img src="<%= user_photo(@conn) %>" class="img-circle">
              </div>
              <div class="nav-item">
                <%= link "Logout", to: session_path(@conn, :delete), method: :delete, class: "nav-link" %>
              </div>
            <% else %>
              <div class="hidden-md-down">
                <img src="/images/user.png" class="img-circle">
              </div>
              <div class="nav-item">
                <a class="nav-link" href="/users/login">Log in</a>
              </div>
              <span class="hidden-md-down">or</span>
              <a class="nav-link" href="/users/signup">Sign up</a>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    <main class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/vue@1.0.28/dist/vue.js"></script>

    <script>
     (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
     m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
     })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
     ga('create', 'UA-85009417-2', 'auto');
     ga('send', 'pageview');</script>
  </body>
</html>