web/router.ex
defmodule Quizler.Router do
  use Quizler.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Quizler.Logger, repo: Quizler.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/users", Quizler do
    pipe_through :browser

    get "/login", SessionController, :new
    post "/login", SessionController, :create

    get "/", UserController, :index
    get "/signup", UserController, :new
    post "/", UserController, :create
    get "/:id", UserController, :show
    delete "/", UserController, :delete
    
    get "/auth/:provider", AuthController, :request
    get "/auth/:provider/callback", AuthController, :callback

    delete "/logout", SessionController, :delete
  end

  scope "/", Quizler do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", PageController, :about

    get "/training", GroupController, :index
    get "/decks/:id/terms/json", DeckController, :terms_json
    get "/decks/:id/terms", DeckController, :terms
    get "/decks/:deck_id/quiz/done", DeckController, :done_quiz
    post "/decks/:deck_id/quiz/done", DeckController, :done_quiz
    get "/decks/:id/quiz", DeckController, :quiz
    get "/decks/:id/quiz_items", DeckController, :quiz_items
    get "/decks/:id/done", DeckController, :done_flashcard
    get "/decks/:deck_id/games/match/cards", Deck.GameController, :game_match_cards
    get "/decks/:deck_id/games/match", Deck.GameController, :game_match
    get "/decks/:deck_id/games/match/done", Deck.GameController, :game_match_done

    get "/groups/all", GroupController, :all
    get "/groups/:id/test", GroupController, :test
    get "/groups/:id/test_items", GroupController, :test_items
    get "/groups/:id/terms", GroupController, :terms
    get "/groups/test_results", GroupController, :test_results
    delete "/groups/test_results/:test_result_id", GroupController, :delete_test_result

    post "/groups/:group_id/test/done", GroupController, :test_done
    resources "/terms", TermController
    resources "/groups", GroupController
    resources "/decks", DeckController
    resources "/logs", LogController

    resources "/test_groups", UserTestGroupController

    resources "/spanish_terms", SpanishTermController

    get "/exams/code/:code", ExamController, :code
    resources "/exams/questions", ExamQuestionController
    get "/exams/results", ExamController, :results
    delete "/exams/results/:result_id", ExamController, :delete_result
    get "/exams/:id/questions", ExamController, :questions
    post "/exams/:exam_id/done", ExamController, :done
    resources "/exams/question_types", ExamQuestionTypeController

    resources "/exams", ExamController
    resources "/user_languages", UserLanguageController
    resources "/languages", LanguageController
    resources "/term_sentences", TermSentenceController
  end


  # Other scopes may use custom stacks.
  # scope "/api", Quizler do
  #   pipe_through :api
  # end
end

web/views/term_view.ex
defmodule Quizler.TermView do
  use Quizler.Web, :view
end

web/templates/term/edit.html.eex
<h2>Edit term</h2>

<%= render "form.html", changeset: @changeset,
                        action: term_path(@conn, :update, @term) %>

<%= link "Delete", to: group_path(@conn, :delete, @group), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
<%= link "Back", to: term_path(@conn, :index) %>

web/templates/term/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :term, class: "control-label" %>
    <%= text_input f, :term, class: "form-control" %>
    <%= error_tag f, :term %>
  </div>

  <div class="form-group">
    <%= label f, :definition, class: "control-label" %>
    <%= text_input f, :definition, class: "form-control" %>
    <%= error_tag f, :definition %>
  </div>

  <div class="form-group">
    <%= label f, :image, class: "control-label" %>
    <%= text_input f, :image, class: "form-control" %>
    <%= error_tag f, :image %>
  </div>

  <div class="form-group">
    <%= label f, :deck_id, class: "control-label" %>
    <%= number_input f, :deck_id, class: "form-control" %>
    <%= error_tag f, :deck_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/term/index.html.eex
<h2>Listing terms</h2>

<table class="table">
  <thead>
    <tr>
      <th>id</th>
      <th>Term</th>
      <th>definition</th>
      <th>image</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for term <- @terms do %>
    <tr>
      <td><%= term.id %></td>
      <td><%= term.term %></td>
      <td><%= term.definition %></td>
      <td><%= term.image %></td>
      <td class="text-right">
        <%= link "Show", to: term_path(@conn, :show, term), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: term_path(@conn, :edit, term), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: term_path(@conn, :delete, term), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New term", to: term_path(@conn, :new) %>

web/templates/term/new.html.eex
<h2>New term</h2>

<%= render "form.html", changeset: @changeset,
                        action: term_path(@conn, :create) %>

<%= link "Back", to: term_path(@conn, :index) %>

web/templates/term/show.html.eex
<h2>Show term</h2>

<ul>

  <li>
    <strong>Term:</strong>
    <%= @term.term %>
  </li>

  <li>
    <strong>Definition:</strong>
    <%= @term.definition %>
  </li>

  <li>
    <strong>Image:</strong>
    <%= @term.image %>
  </li>

</ul>

<%= link "Edit", to: term_path(@conn, :edit, @term) %>
<%= link "Back", to: term_path(@conn, :index) %>