web/router.ex
defmodule Quizler.Router do
  use Quizler.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Quizler.Logger, repo: Quizler.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/users", Quizler do
    pipe_through :browser

    get "/login", SessionController, :new
    post "/login", SessionController, :create

    get "/", UserController, :index
    get "/signup", UserController, :new
    post "/", UserController, :create
    get "/:id", UserController, :show
    delete "/", UserController, :delete
    
    get "/auth/:provider", AuthController, :request
    get "/auth/:provider/callback", AuthController, :callback

    delete "/logout", SessionController, :delete
  end

  scope "/", Quizler do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", PageController, :about

    get "/training", GroupController, :index
    get "/decks/:id/terms/json", DeckController, :terms_json
    get "/decks/:id/terms", DeckController, :terms
    get "/decks/:deck_id/quiz/done", DeckController, :done_quiz
    post "/decks/:deck_id/quiz/done", DeckController, :done_quiz
    get "/decks/:id/quiz", DeckController, :quiz
    get "/decks/:id/quiz_items", DeckController, :quiz_items
    get "/decks/:id/done", DeckController, :done_flashcard
    get "/decks/:deck_id/games/match/cards", Deck.GameController, :game_match_cards
    get "/decks/:deck_id/games/match", Deck.GameController, :game_match
    get "/decks/:deck_id/games/match/done", Deck.GameController, :game_match_done

    get "/groups/all", GroupController, :all
    get "/groups/:id/test", GroupController, :test
    get "/groups/:id/test_items", GroupController, :test_items
    get "/groups/:id/terms", GroupController, :terms
    get "/groups/test_results", GroupController, :test_results
    delete "/groups/test_results/:test_result_id", GroupController, :delete_test_result

    post "/groups/:group_id/test/done", GroupController, :test_done
    resources "/terms", TermController
    resources "/groups", GroupController
    resources "/decks", DeckController
    resources "/logs", LogController

    resources "/test_groups", UserTestGroupController

    resources "/spanish_terms", SpanishTermController

    get "/exams/code/:code", ExamController, :code
    resources "/exams/questions", ExamQuestionController
    get "/exams/results", ExamController, :results
    delete "/exams/results/:result_id", ExamController, :delete_result
    get "/exams/:id/questions", ExamController, :questions
    post "/exams/:exam_id/done", ExamController, :done
    resources "/exams/question_types", ExamQuestionTypeController

    resources "/exams", ExamController
    resources "/user_languages", UserLanguageController
    resources "/languages", LanguageController
    resources "/term_sentences", TermSentenceController
  end


  # Other scopes may use custom stacks.
  # scope "/api", Quizler do
  #   pipe_through :api
  # end
end

web/exam/question_controller.ex
defmodule Quizler.ExamQuestionController do
  use Quizler.Web, :controller

  alias Quizler.ExamQuestion
  plug Quizler.Admin

  def index(conn, _params) do
    exam_questions = Repo.all(ExamQuestion)
    render(conn, "index.html", exam_questions: exam_questions)
  end

  def new(conn, _params) do
    changeset = ExamQuestion.changeset(%ExamQuestion{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"exam_question" => exam_question_params}) do
    changeset = ExamQuestion.changeset(%ExamQuestion{}, exam_question_params)

    case Repo.insert(changeset) do
      {:ok, _exam_question} ->
        conn
        |> put_flash(:info, "Exam question created successfully.")
        |> redirect(to: exam_question_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    exam_question = Repo.get!(ExamQuestion, id)
    render(conn, "show.html", exam_question: exam_question)
  end

  def edit(conn, %{"id" => id}) do
    exam_question = Repo.get!(ExamQuestion, id)
    changeset = ExamQuestion.changeset(exam_question)
    render(conn, "edit.html", exam_question: exam_question, changeset: changeset)
  end

  def update(conn, %{"id" => id, "exam_question" => exam_question_params}) do
    exam_question = Repo.get!(ExamQuestion, id)
    changeset = ExamQuestion.changeset(exam_question, exam_question_params)

    case Repo.update(changeset) do
      {:ok, exam_question} ->
        conn
        |> put_flash(:info, "Exam question updated successfully.")
        |> redirect(to: exam_question_path(conn, :show, exam_question))
      {:error, changeset} ->
        render(conn, "edit.html", exam_question: exam_question, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    exam_question = Repo.get!(ExamQuestion, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(exam_question)

    conn
    |> put_flash(:info, "Exam question deleted successfully.")
    |> redirect(to: exam_question_path(conn, :index))
  end
end

web/exam/question_type_controller.ex
defmodule Quizler.ExamQuestionTypeController do
  use Quizler.Web, :controller

  alias Quizler.ExamQuestionType
  plug Quizler.Admin

  def index(conn, _params) do
    exam_question_types = Repo.all(ExamQuestionType)
    render(conn, "index.html", exam_question_types: exam_question_types)
  end

  def new(conn, _params) do
    changeset = ExamQuestionType.changeset(%ExamQuestionType{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"exam_question_type" => exam_question_type_params}) do
    changeset = ExamQuestionType.changeset(%ExamQuestionType{}, exam_question_type_params)

    case Repo.insert(changeset) do
      {:ok, _exam_question_type} ->
        conn
        |> put_flash(:info, "Exam question type created successfully.")
        |> redirect(to: exam_question_type_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    exam_question_type = Repo.get!(ExamQuestionType, id)
    render(conn, "show.html", exam_question_type: exam_question_type)
  end

  def edit(conn, %{"id" => id}) do
    exam_question_type = Repo.get!(ExamQuestionType, id)
    changeset = ExamQuestionType.changeset(exam_question_type)
    render(conn, "edit.html", exam_question_type: exam_question_type, changeset: changeset)
  end

  def update(conn, %{"id" => id, "exam_question_type" => exam_question_type_params}) do
    exam_question_type = Repo.get!(ExamQuestionType, id)
    changeset = ExamQuestionType.changeset(exam_question_type, exam_question_type_params)

    case Repo.update(changeset) do
      {:ok, exam_question_type} ->
        conn
        |> put_flash(:info, "Exam question type updated successfully.")
        |> redirect(to: exam_question_type_path(conn, :show, exam_question_type))
      {:error, changeset} ->
        render(conn, "edit.html", exam_question_type: exam_question_type, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    exam_question_type = Repo.get!(ExamQuestionType, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(exam_question_type)

    conn
    |> put_flash(:info, "Exam question type deleted successfully.")
    |> redirect(to: exam_question_type_path(conn, :index))
  end
end

web/views/exam_view.ex
defmodule Quizler.ExamView do
  use Quizler.Web, :view

  def render("questions.json", %{exam: exam}) do
    %{
      name: exam.name,
      grouped_questions: exam.grouped_questions
    }
  end

  def score(exam) do
    result = hd(exam.results)
    num_of_questions = length(exam.questions)
    num_of_wrong = length(result.wrong_answers)
    "#{num_of_questions - num_of_wrong}/#{num_of_questions}"
  end

  def result(question) do
    if (question.answer == question.user_answer) do
      "text-success"
    else
      "text-danger"
    end
  end

end

web/templates/exam/done.html.eex
<div class="exam card">
  <h1><%= @exam.name %></h1>
  <h2>Score: <span class="text-success"><%= score(@exam) %></span></h2>
  <%= for group <- @exam.grouped_questions do %>
    <h3><%= group.name %></h3>
    <%= for question <- group.questions, 1..3 do %>
    <div class="result_area">
      <div class="question"><%= raw question.question %></div>
      <div class="info">Answer: <span class="answer <%= result(question) %>"><%= question.answer %></span></div>
      <div class="info">Your answer: <span class="user_answer <%= result(question) %>"><%= question.user_answer %></span></div>
    </div>
    <% end %>
  <% end %>
</div>

web/templates/exam/edit.html.eex
<h2>Edit exam</h2>

<%= render "form.html", changeset: @changeset,
                        action: exam_path(@conn, :update, @exam) %>

<%= link "Delete", to: exam_path(@conn, :delete, @exam), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
<%= link "Back", to: exam_path(@conn, :index) %>

web/templates/exam/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/exam/index.html.eex
<div class="group exam">
<%= for exam <- @exams do %>
    <div class="col-lg-3 section">
      <a href="<%= exam_path(@conn, :show, exam) %>">
        <div class="info circle">
          <h3 class="title"><%= exam.name %></h3>
        </div>
      </a>
    </div>
<% end %>
</div>

web/templates/exam/new.html.eex
<h2>New exam</h2>

<%= render "form.html", changeset: @changeset,
                        action: exam_path(@conn, :create) %>

<%= link "Back", to: exam_path(@conn, :index) %>

web/templates/exam/results.html.eex
<h1>Exam Results</h1>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>User id</th>
      <th>Exam ID</th>
      <th>Wrong Answers</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for result <- @results do %>
    <tr>
      <td><%= result.id %></td>
      <td><%= result.user_id %></td>
      <td><%= result.exam_id %></td>
      <td><%= Enum.join(result.wrong_answers, ", ") %></td>
      <td><%= link "Delete", to: exam_path(@conn, :delete_result, result.id), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/exam/show.html.eex
<div class="content exam" id="exam">
  <h1><%= @exam.name %></h1>
  <h2>{{group.name}}</h2>
  <p>{{group.instructions}}</p>
  <div class="card">
    <div class="question-area" v-for="item in group.questions">
      <h4 class="question">{{{ item.question }}}</h4>
      <ul class="answer">
        <li v-for="choice in item.choices">
          <label>
            <input name="{{item.id}}_answer" type="radio" value="{{ choice }}" v-model="item.user_answer"> {{ choice }}
          </label>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="content_nav">
    <button class="btn btn-primary" v-show="last_group" v-on:click="submit_answer" id="submit_answer_btn">Submit</button>
    <button class="btn btn-primary" v-show="!last_group" v-on:click="next" id="next_btn">Next</button>
  </div>
  <div class="hidden">
    <%= form_for @conn, exam_path(@conn, :done, @exam), [as: :result, id: "done_exam_form"], fn f -> %>
        <div v-for="group in grouped_questions">
          <div v-for="item in group.questions">
            <input type="text" name="answers[{{item.id}}]" value="{{item.user_answer}}"/>
          </div>
        </div>
      <%= submit "Submit" %>
    <% end %>
  </div>
</div>


<script type="text/javascript">
 $(document).ready(function() {
   var question_url = "<%= exam_path(@conn, :questions, @exam) %>";
   var vueAppName = "#exam";
   var done_url = "<%= exam_path(@conn, :done, @exam) %>";

   $.get( question_url )
   .done(function( data ) {
     var grouped_questions = data.grouped_questions;

     var index = 0;
     var size = grouped_questions.length;
     var group = grouped_questions[index];

     new Vue({
       el: vueAppName,
       data: {
         group: group,
         completed: 0,
         size: size,
         last_group: size == 1,
         grouped_questions: grouped_questions
       },
       methods: {
         next: function(event) {

           index++;
           if (index == size) {

           } else if (index == (size - 1)) {
             this.last_group = true;
             this.group = grouped_questions[index];
           } else {
             this.group = grouped_questions[index];
           }
         },
         submit_answer: function(event) {
           $('#done_exam_form').submit();
         }
       }
     }); //end of Vue
     $('.loading').hide();
     $('.content').show();
   }); //end of get
 });

</script>